spring:
  application:
    name: todo-app
  datasource:
    url: jdbc:postgres://student_ogkx_user:xiIAUPN0BFj04PIstIoCpEpXqMJ7f8kS@dpg-co7o2ecf7o1s738js3g0-a/student_ogkx
    password: xiIAUPN0BFj04PIstIoCpEpXqMJ7f8kS
    username: student_ogkx_user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
