spring:
  application:
    name: todo-app
  datasource:
    url: jdbc:postgresql://dpg-cpmoghmehbks73fs7ft0-a.singapore-postgres.render.com:5432/dbtest_w2xr
    password: CV7zgtqsz1uh6Ljqg5HmQxhgbLVRYZL2
    username: dbtest_w2xr_user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
